# Auto-generated by rust2cython. Do not edit.

cimport bio_sequence

# WARNING: String-returning functions require the Rust side to use
# CString::into_raw(). See README for memory safety notes.

def count_nucleotide(sequence, nucleotide) -> int:
    cdef bytes _sequence_b = sequence.encode('utf-8')
    cdef bytes _nucleotide_b = nucleotide.encode('utf-8')
    cdef int _result = bio_sequence.count_nucleotide(_sequence_b, _nucleotide_b)
    return _result

def gc_content(sequence) -> float:
    cdef bytes _sequence_b = sequence.encode('utf-8')
    cdef double _result = bio_sequence.gc_content(_sequence_b)
    return _result

def reverse_complement(sequence) -> str:
    # Note: Rust must return this as CString (std::ffi::CString::into_raw)
    cdef bytes _sequence_b = sequence.encode('utf-8')
    cdef const char* _result = bio_sequence.reverse_complement(_sequence_b)
    return _result.decode('utf-8')

def contains_motif(sequence, motif) -> bool:
    cdef bytes _sequence_b = sequence.encode('utf-8')
    cdef bytes _motif_b = motif.encode('utf-8')
    cdef bint _result = bio_sequence.contains_motif(_sequence_b, _motif_b)
    return _result

