# Auto-generated by rust2cython. Do not edit.

cdef extern from "bio_sequence.h":

    int count_nucleotide(const char* sequence, const char* nucleotide)

    double gc_content(const char* sequence)

    const char* reverse_complement(const char* sequence)

    bint contains_motif(const char* sequence, const char* motif)

