# Auto-generated by rust2cython. Do not edit.

cimport linear_algebra
import numpy as np

cdef class Matrix2x2:
    cdef linear_algebra.Matrix2x2 _c
    def __init__(self, double a, double b, double c, double d):
        self._c.a = a
        self._c.b = b
        self._c.c = c
        self._c.d = d

def dot_product(a, b) -> float:
    cdef double[::1] _a_mv = np.asarray(a, dtype=np.float64)
    # pass pointer to data start
    cdef double[::1] _b_mv = np.asarray(b, dtype=np.float64)
    # pass pointer to data start
    cdef double _result = linear_algebra.dot_product(&_a_mv[0], &_b_mv[0])
    return _result

def scale(v, factor) -> list:
    cdef double[::1] _v_mv = np.asarray(v, dtype=np.float64)
    # pass pointer to data start
    cdef double[:] _result = linear_algebra.scale(&_v_mv[0], factor)
    return _result

def norm(v) -> float:
    cdef double[::1] _v_mv = np.asarray(v, dtype=np.float64)
    # pass pointer to data start
    cdef double _result = linear_algebra.norm(&_v_mv[0])
    return _result

def determinant(m: Matrix2x2) -> float:
    cdef double _result = linear_algebra.determinant(m._c)
    return _result

