# Auto-generated by rust2cython. Do not edit.

import numpy as np


cdef extern from "linear_algebra.h":

    ctypedef struct CMatrix2x2 "Matrix2x2":
        double a
        double b
        double c
        double d

    double c_dot_product "dot_product"(const double* a, size_t a_len,
                                       const double* b, size_t b_len)

    double c_norm "norm"(const double* v, size_t v_len)

    void c_scale "scale"(const double* v, size_t v_len,
               double factor,
               double* out, size_t out_len)

    double c_determinant "determinant"(CMatrix2x2 m)


cdef class Matrix2x2:
    cdef CMatrix2x2 _c
    def __init__(self, double a, double b, double c, double d):
        self._c.a = a
        self._c.b = b
        self._c.c = c
        self._c.d = d

def dot_product(a, b) -> float:
    cdef double[::1] _a = np.asarray(a, dtype=np.float64)
    cdef double[::1] _b = np.asarray(b, dtype=np.float64)
    return c_dot_product(&_a[0], len(_a), &_b[0], len(_b))

def norm(v) -> float:
    cdef double[::1] _v = np.asarray(v, dtype=np.float64)
    return c_norm(&_v[0], len(_v))

def scale(v, double factor):
    cdef double[::1] _v = np.asarray(v, dtype=np.float64)
    cdef double[::1] _out = np.zeros(len(_v), dtype=np.float64)
    c_scale(&_v[0], len(_v), factor, &_out[0], len(_out))
    return np.asarray(_out)

def determinant(m: Matrix2x2) -> float:
    return c_determinant(m._c)

