# Auto-generated by rust2cython. Do not edit.

cdef extern from "linear_algebra.h":

    ctypedef struct Matrix2x2:
        double a
        double b
        double c
        double d

    double dot_product(double[:] a, double[:] b)

    double[:] scale(double[:] v, double factor)

    double norm(double[:] v)

    double determinant(Matrix2x2 m)

