#pragma once
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* Auto-generated by rust2cython. Do not edit. */

typedef struct {
    size_t start;
    size_t end;
    uint32_t k;
} Match;

typedef struct {
    EditType edit;
    size_t count;
} Edit;

void alloc_str(size_t len, uint8_t* out, size_t out_len);

void fill_str(unknown dest, unknown src);

void rust2cython_free_string(char* ptr);
void rust2cython_free_string_array(char** ptr, size_t len);

