# Auto-generated by rust2cython. Do not edit.

from libc.stddef cimport size_t

cdef extern from "triple_accel.h":

    void rust2cython_free_string(char* ptr)
    void rust2cython_free_string_array(char** ptr, size_t len)

    ctypedef struct CMatch "Match":
        int start
        int end
        int k

    ctypedef struct CEdit "Edit":
        EditType edit
        int count

    void c_alloc_str "alloc_str"(int len, int* out, size_t out_len)

    # WARNING: skipped fill_str, unknown type unknown

cpdef enum EditType:
    Match
    Mismatch
    AGap
    BGap
    Transpose

cpdef enum SearchType:
    All
    Best

