# Auto-generated by rust2cython. Do not edit.

from libc.stddef cimport size_t
from libc.stdlib cimport free, malloc
import numpy as np

cdef extern from "triple_accel.h":

    void rust2cython_free_string(char* ptr)
    void rust2cython_free_string_array(char** ptr, size_t len)

    ctypedef struct CMatch "Match":
        int start
        int end
        int k

    ctypedef struct CEdit "Edit":
        EditType edit
        int count

    void c_alloc_str "alloc_str"(int len, int* out, size_t out_len)

    void c_fill_str "fill_str"(Cunknown dest, Cunknown src)


cdef class Match:
    cdef CMatch _c
    def __init__(self, int start, int end, int k):
        self._c.start = start
        self._c.end = end
        self._c.k = k

cdef class Edit:
    cdef CEdit _c
    def __init__(self, EditType edit, int count):
        self._c.edit = edit
        self._c.count = count

def alloc_str(len):
# WARNING: skipped fill_str, unknown named

