// Auto-generated by rust2cython. Add this file to your crate.
// Call super::<fn_name>(...) to invoke your original functions.


// Ensure Matrix2x2 is #[repr(C)] in your original code

#[no_mangle]
pub unsafe extern "C" fn dot_product(a: *const f64, a_len: usize, b: *const f64, b_len: usize) -> f64 {
    let a_slice = unsafe { std::slice::from_raw_parts(a, a_len) };
    let b_slice = unsafe { std::slice::from_raw_parts(b, b_len) };
    return super::dot_product(a_slice.to_vec(), b_slice.to_vec());
}

#[no_mangle]
pub unsafe extern "C" fn scale(v: *const f64, v_len: usize, factor: f64, out: *mut f64, out_len: usize) -> () {
    let v_slice = unsafe { std::slice::from_raw_parts(v, v_len) };
    let v = super::scale(v_slice.to_vec(), factor);
    let out_slice = unsafe { std::slice::from_raw_parts_mut(out, out_len.min(v.len())) };
    out_slice.copy_from_slice(&v[..out_slice.len()]);
}

#[no_mangle]
pub unsafe extern "C" fn norm(v: *const f64, v_len: usize) -> f64 {
    let v_slice = unsafe { std::slice::from_raw_parts(v, v_len) };
    return super::norm(v_slice.to_vec());
}

#[no_mangle]
pub unsafe extern "C" fn determinant(m: super::Matrix2x2) -> f64 {
    return super::determinant(m);
}

