#pragma once
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* Auto-generated by rust2cython. Do not edit. */

typedef struct {
    int32_t match_score;
    int32_t mismatch_score;
} MatchParams;

typedef struct {
    int32_t gap_open;
    int32_t gap_extend;
    F match_fn;
    /* unsupported field type */ match_scores;
    int32_t xclip_prefix;
    int32_t xclip_suffix;
    int32_t yclip_prefix;
    int32_t yclip_suffix;
} Scoring;

typedef struct {
    unknown I;
    unknown D;
    unknown S;
    const size_t* /* Lx_len */ Lx;
    const size_t* /* Ly_len */ Ly;
    const int32_t* /* Sn_len */ Sn;
    Traceback traceback;
    Scoring scoring;
} Aligner;

typedef struct {
    uint16_t v;
} TracebackCell;

void rust2cython_free_string(char* ptr);
void rust2cython_free_string_array(char** ptr, size_t len);

