# Auto-generated by rust2cython. Do not edit.

from libc.stddef cimport size_t

cdef extern from "rust_bio_align.h":

    void rust2cython_free_string(char* ptr)
    void rust2cython_free_string_array(char** ptr, size_t len)

    ctypedef struct CMatchParams "MatchParams":
        int match_score
        int mismatch_score

    ctypedef struct CScoring "Scoring":
        int gap_open
        int gap_extend
        F match_fn
        unknown match_scores
        int xclip_prefix
        int xclip_suffix
        int yclip_prefix
        int yclip_suffix

    ctypedef struct CAligner "Aligner":
        unknown I
        unknown D
        unknown S
        int[:] Lx
        int[:] Ly
        int[:] Sn
        Traceback traceback
        Scoring scoring

    ctypedef struct CTracebackCell "TracebackCell":
        int v

