# Auto-generated by rust2cython. Do not edit.

from libc.stddef cimport size_t
from libc.stdlib cimport free, malloc
import numpy as np

cdef extern from "rust_bio_align.h":

    void rust2cython_free_string(char* ptr)
    void rust2cython_free_string_array(char** ptr, size_t len)

    ctypedef struct CMatchParams "MatchParams":
        int match_score
        int mismatch_score

    ctypedef struct CScoring "Scoring":
        int gap_open
        int gap_extend
        F match_fn
        unknown match_scores
        int xclip_prefix
        int xclip_suffix
        int yclip_prefix
        int yclip_suffix

    ctypedef struct CAligner "Aligner":
        unknown I
        unknown D
        unknown S
        int[:] Lx
        int[:] Ly
        int[:] Sn
        Traceback traceback
        Scoring scoring

    ctypedef struct CTracebackCell "TracebackCell":
        int v


cdef class MatchParams:
    cdef CMatchParams _c
    def __init__(self, int match_score, int mismatch_score):
        self._c.match_score = match_score
        self._c.mismatch_score = mismatch_score

cdef class Scoring:
    cdef CScoring _c
    def __init__(self, int gap_open, int gap_extend, F match_fn, unknown match_scores, int xclip_prefix, int xclip_suffix, int yclip_prefix, int yclip_suffix):
        self._c.gap_open = gap_open
        self._c.gap_extend = gap_extend
        self._c.match_fn = match_fn
        self._c.match_scores = match_scores
        self._c.xclip_prefix = xclip_prefix
        self._c.xclip_suffix = xclip_suffix
        self._c.yclip_prefix = yclip_prefix
        self._c.yclip_suffix = yclip_suffix

cdef class Aligner:
    cdef CAligner _c
    def __init__(self, unknown I, unknown D, unknown S, int[:] Lx, int[:] Ly, int[:] Sn, Traceback traceback, Scoring scoring):
        self._c.I = I
        self._c.D = D
        self._c.S = S
        self._c.Lx = Lx
        self._c.Ly = Ly
        self._c.Sn = Sn
        self._c.traceback = traceback
        self._c.scoring = scoring

cdef class TracebackCell:
    cdef CTracebackCell _c
    def __init__(self, int v):
        self._c.v = v

