# Auto-generated by rust2cython. Do not edit.

from libc.stddef cimport size_t
from libc.stdlib cimport free
import numpy as np

cdef extern from "linear_algebra.h":

    ctypedef struct CMatrix2x2 "Matrix2x2":
        double a
        double b
        double c
        double d

    double c_dot_product "dot_product"(const double* a, size_t a_len, const double* b, size_t b_len)

    void c_scale "scale"(const double* v, size_t v_len, double factor, double* out, size_t out_len)

    double c_norm "norm"(const double* v, size_t v_len)

    double c_determinant "determinant"(CMatrix2x2 m)


cdef class Matrix2x2:
    cdef CMatrix2x2 _c
    def __init__(self, double a, double b, double c, double d):
        self._c.a = a
        self._c.b = b
        self._c.c = c
        self._c.d = d

def dot_product(a, b) -> float:
    cdef double[::1] _a_mv = np.asarray(a, dtype=np.float64)
    cdef double[::1] _b_mv = np.asarray(b, dtype=np.float64)
    cdef double _result = c_dot_product(&_a_mv[0], len(_a_mv), &_b_mv[0], len(_b_mv))
    return _result

def scale(v, factor):
    cdef double[::1] _v_mv = np.asarray(v, dtype=np.float64)
    cdef double[::1] _out = np.zeros(len(_v_mv), dtype=np.float64)
    c_scale(&_v_mv[0], len(_v_mv), factor, &_out[0], len(_out))
    return np.asarray(_out)

def norm(v) -> float:
    cdef double[::1] _v_mv = np.asarray(v, dtype=np.float64)
    cdef double _result = c_norm(&_v_mv[0], len(_v_mv))
    return _result

def determinant(m: Matrix2x2) -> float:
    cdef CMatrix2x2 _m_c = m._c
    cdef double _result = c_determinant(_m_c)
    return _result

