#pragma once
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* Auto-generated by rust2cython. Do not edit. */

typedef struct {
    double a;
    double b;
    double c;
    double d;
} Matrix2x2;

double dot_product(const double* a, size_t a_len, const double* b, size_t b_len);

void scale(const double* v, size_t v_len, double factor, double* out, size_t out_len);

double norm(const double* v, size_t v_len);

double determinant(Matrix2x2 m);

