# Auto-generated by rust2cython. Do not edit.

from libc.stddef cimport size_t
from libc.stdlib cimport free, malloc
import numpy as np

cdef extern from "rust_bio_gc.h":

    void rust2cython_free_string(char* ptr)
    void rust2cython_free_string_array(char** ptr, size_t len)

    float c_gc_content "gc_content"(CT sequence)

    float c_gc3_content "gc3_content"(CT sequence)


# WARNING: skipped gc_content, unknown named

# WARNING: skipped gc3_content, unknown named

