# Auto-generated by rust2cython. Do not edit.

from libc.stddef cimport size_t

cdef extern from "rust_bio_gc.h":

    void rust2cython_free_string(char* ptr)
    void rust2cython_free_string_array(char** ptr, size_t len)

    # WARNING: skipped gc_content, unknown type T

    # WARNING: skipped gc3_content, unknown type T

