#pragma once
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* Auto-generated by rust2cython. Do not edit. */

void rust2cython_free_string(char* ptr);
void rust2cython_free_string_array(char** ptr, size_t len);

