# Auto-generated by rust2cython. Do not edit.

from libc.stddef cimport size_t

cdef extern from "statrs.h":

    void rust2cython_free_string(char* ptr)
    void rust2cython_free_string_array(char** ptr, size_t len)

