# Auto-generated by rust2cython. Do not edit.

cdef extern from "complex.h":

    # Note: Rust param/return must use *const <type> (not Option<T> directly)
    const double* maybe_sqrt(double x)

    int safe_div(int a, int b, char** error_out)

    double sum_vec(double[:] values)

    # Note: Rust param/return must use *const <type> (not Option<T> directly)
    double clamp(const double* x)

