# Auto-generated by rust2cython. Do not edit.

cimport complex
import numpy as np

from libc.stdlib cimport free

def maybe_sqrt(x) -> float:
    # Note: Rust param/return must use *const <type> (not Option<T> directly)
    cdef const double* _result = complex.maybe_sqrt(x)
    return None if _result is NULL else _result[0]

def safe_div(a, b) -> int:
    # Note: Rust must use CString::into_raw() for the error string.
    # The generated wrapper does NOT free the error string (memory leak risk).
    # See README for how to implement free_rust_string() in your Rust lib.
    cdef char* _err = NULL
    cdef int _result = complex.safe_div(a, b, &_err)
    if _err is not NULL:
        msg = _err.decode('utf-8')
        raise RuntimeError(msg)
    return _result

def sum_vec(values) -> float:
    cdef double[::1] _values_mv = np.asarray(values, dtype=np.float64)
    # pass pointer to data start
    cdef double _result = complex.sum_vec(&_values_mv[0])
    return _result

def clamp(x) -> float:
    # Note: Rust param/return must use *const <type> (not Option<T> directly)
    cdef double _x_val
    cdef const double* _x_ptr
    if x is None:
        _x_ptr = NULL
    else:
        _x_val = x
        _x_ptr = &_x_val
    cdef double _result = complex.clamp(_x_ptr)
    return _result

