# Auto-generated by rust2cython. Do not edit.

cimport simple

# add is available directly as simple.add

# scale is available directly as simple.scale

# is_positive is available directly as simple.is_positive

