# Auto-generated by rust2cython. Do not edit.

cdef extern from "strings.h":

    const char* greet(const char* name)

    const char* repeat(const char* s, int n)

    int byte_length(const char* s)

