# Auto-generated by rust2cython. Do not edit.

cimport strings

# WARNING: String-returning functions require the Rust side to use
# CString::into_raw(). See README for memory safety notes.

def greet(name) -> str:
    # Note: Rust must return this as CString (std::ffi::CString::into_raw)
    cdef bytes _name_b = name.encode('utf-8')
    cdef const char* _result = strings.greet(_name_b)
    return _result.decode('utf-8')

def repeat(s, n) -> str:
    # Note: Rust must return this as CString (std::ffi::CString::into_raw)
    cdef bytes _s_b = s.encode('utf-8')
    cdef const char* _result = strings.repeat(_s_b, n)
    return _result.decode('utf-8')

def byte_length(s) -> int:
    cdef bytes _s_b = s.encode('utf-8')
    cdef int _result = strings.byte_length(_s_b)
    return _result

