# Auto-generated by rust2cython. Do not edit.

cdef extern from "structs.h":

    ctypedef struct Point:
        double x
        double y

    ctypedef struct Color:
        int r
        int g
        int b

    double distance(Point p)

    Color blend(Color a, Color b)

