# Auto-generated by rust2cython. Do not edit.

cimport structs

cdef class Point:
    cdef structs.Point _c
    def __init__(self, double x, double y):
        self._c.x = x
        self._c.y = y

cdef class Color:
    cdef structs.Color _c
    def __init__(self, int r, int g, int b):
        self._c.r = r
        self._c.g = g
        self._c.b = b

def distance(p: Point) -> float:
    cdef double _result = structs.distance(p._c)
    return _result

def blend(a: Color, b: Color) -> Color:
    cdef structs.Color _result = structs.blend(a._c, b._c)
    out = Color.__new__(Color)
    out._c = _result
    return out

