pub fn generate_header(module: &crate::ir::Module, _lib_name: &str) -> String {
    use crate::ir::TypeRef;

    fn prim_to_c(ty: &TypeRef) -> Option<String> {
        use crate::ir::PrimKind::*;
        match ty {
            TypeRef::Primitive(I8) => Some("int8_t".to_string()),
            TypeRef::Primitive(I16) => Some("int16_t".to_string()),
            TypeRef::Primitive(I32) => Some("int32_t".to_string()),
            TypeRef::Primitive(I64) => Some("int64_t".to_string()),
            TypeRef::Primitive(U8) => Some("uint8_t".to_string()),
            TypeRef::Primitive(U16) => Some("uint16_t".to_string()),
            TypeRef::Primitive(U32) => Some("uint32_t".to_string()),
            TypeRef::Primitive(U64) => Some("uint64_t".to_string()),
            TypeRef::Primitive(F32) => Some("float".to_string()),
            TypeRef::Primitive(F64) => Some("double".to_string()),
            TypeRef::Primitive(Bool) => Some("bool".to_string()),
            TypeRef::Primitive(Usize) => Some("size_t".to_string()),
            _ => None,
        }
    }

    let mut out = String::new();
    out.push_str("#pragma once\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stddef.h>\n");
    out.push_str("#include <stdbool.h>\n\n");
    out.push_str("/* Auto-generated by rust2cython. Do not edit. */\n\n");

    // Structs
    for s in &module.structs {
        out.push_str("typedef struct {\n");
        for f in &s.fields {
            let cty = match &f.ty {
                TypeRef::Primitive(_) => prim_to_c(&f.ty).unwrap(),
                TypeRef::Str => "const char*".to_string(),
                TypeRef::Named(n) => n.clone(),
                TypeRef::Void => "void".to_string(),
                other => {
                    match other {
                        TypeRef::Vec(inner) => {
                            if let Some(pic) = prim_to_c(inner) {
                                format!("const {0}* /* {1}_len */", pic, f.name)
                            } else {
                                "/* unsupported field type */".to_string()
                            }
                        }
                        _ => "/* unsupported field type */".to_string(),
                    }
                }
            };
            out.push_str(&format!("    {} {};\n", cty, f.name));
        }
        out.push_str(&format!("}} {};\n\n", s.name));
    }

    // Functions
    for fn_def in &module.functions {
        let mut unsupported = None::<String>;

        fn map_type(ty: &TypeRef, prim_to_c: &dyn Fn(&TypeRef) -> Option<String>) -> Result<String, String> {
            match ty {
                TypeRef::Primitive(_) => Ok(prim_to_c(ty).unwrap()),
                TypeRef::Str => Ok("const char*".to_string()),
                TypeRef::Named(n) => Ok(n.clone()),
                TypeRef::Void => Ok("void".to_string()),
                TypeRef::Vec(inner) => {
                    if let Some(c) = prim_to_c(inner) {
                        Ok(format!("const {}* /*ptr*/, size_t /*len*/", c))
                    } else {
                        Err("Vec<non-primitive> not supported".to_string())
                    }
                }
                TypeRef::Option(inner) => {
                    if let Some(c) = prim_to_c(inner) {
                        Ok(format!("const {}*", c))
                    } else {
                        Err("Option<non-primitive> not supported".to_string())
                    }
                }
                TypeRef::Result(ok, _err) => {
                    if let Some(c) = prim_to_c(ok) {
                        Ok(c)
                    } else {
                        Err("Result<non-primitive,_> not supported".to_string())
                    }
                }
                TypeRef::Ptr(_) => Err("pointer types not supported".to_string()),
            }
        }

        let mut params_out: Vec<String> = Vec::new();
        for p in &fn_def.params {
            match &p.ty {
                TypeRef::Vec(inner) => {
                    if let Some(c) = prim_to_c(inner) {
                        params_out.push(format!("const {}* {}, size_t {}_len", c, p.name, p.name));
                    } else {
                        unsupported = Some(format!("Vec<non-primitive> in param {}", p.name));
                        break;
                    }
                }
                TypeRef::Option(inner) => {
                    if let Some(c) = prim_to_c(inner) {
                        params_out.push(format!("const {}* {}", c, p.name));
                    } else {
                        unsupported = Some(format!("Option<non-primitive> in param {}", p.name));
                        break;
                    }
                }
                other => {
                    match map_type(other, &prim_to_c) {
                        Ok(s) => params_out.push(format!("{} {}", s, p.name)),
                        Err(e) => { unsupported = Some(e); break; }
                    }
                }
            }
        }

        if unsupported.is_some() {
            out.push_str(&format!("/* skipped: {} — {} */\n\n", fn_def.name, unsupported.unwrap()));
            continue;
        }

        let mut ret_extra: Vec<String> = Vec::new();
        let ret_type = match &fn_def.ret {
            TypeRef::Vec(inner) => {
                if let Some(c) = prim_to_c(inner) {
                    ret_extra.push(format!("{}* out", c));
                    ret_extra.push("size_t out_len".to_string());
                    "void".to_string()
                } else {
                    out.push_str(&format!("/* skipped: {} — Vec<non-primitive> return */\n\n", fn_def.name));
                    continue;
                }
            }
            TypeRef::Option(inner) => {
                if let Some(c) = prim_to_c(inner) { format!("const {}*", c) } else { out.push_str(&format!("/* skipped: {} — Option<non-primitive> return */\n\n", fn_def.name)); continue; }
            }
            TypeRef::Result(ok, _err) => {
                if let Some(c) = prim_to_c(ok) { c } else { out.push_str(&format!("/* skipped: {} — Result<non-primitive,_> return */\n\n", fn_def.name)); continue; }
            }
            other => {
                match map_type(other, &prim_to_c) {
                    Ok(s) => s,
                    Err(e) => { out.push_str(&format!("/* skipped: {} — {} */\n\n", fn_def.name, e)); continue; }
                }
            }
        };

        for ep in ret_extra.iter() {
            params_out.push(ep.clone());
        }

        let params_joined = params_out.join(", ");
        out.push_str(&format!("{} {}({});\n\n", ret_type, fn_def.name, params_joined));
    }

    out
}
