use crate::ir::TypeRef;

const CYTHON_KEYWORDS: &[&str] = &[
    "raise",
    "except",
    "import",
    "return",
    "pass",
    "class",
    "def",
    "cdef",
    "cpdef",
    "extern",
    "from",
    "with",
    "as",
    "in",
    "not",
    "and",
    "or",
    "is",
    "lambda",
    "yield",
    "global",
    "del",
    "print",
    "exec",
    "assert",
    "break",
    "continue",
    "for",
    "while",
    "if",
    "elif",
    "else",
    "try",
    "finally",
    "cimport",
    "include",
    "ctypedef",
    "struct",
    "union",
    "enum",
    "void",
    "char",
    "int",
    "long",
    "float",
    "double",
    "bint",
    "object",
    "list",
    "dict",
    "tuple",
    "set",
    "bytes",
    "bytearray",
    "unicode",
    "str",
    "bool",
    "complex",
    "type",
    "property",
    "readonly",
    "public",
    "api",
    "inline",
    "nogil",
    "gil",
];

pub(crate) fn cython_ident(name: &str) -> (String, Option<String>) {
    if CYTHON_KEYWORDS.contains(&name) {
        (
            format!("{} _", name).replace(" _", "_"),
            Some(name.to_string()),
        )
    } else {
        (name.to_string(), None)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum StructEmitMode {
    Full,
    Partial,
    Opaque,
}

pub(crate) fn field_is_concrete(
    ty: &TypeRef,
    struct_names: &std::collections::HashSet<String>,
) -> bool {
    match ty {
        TypeRef::Primitive(_) => true,
        TypeRef::Named(name) => struct_names.contains(name),
        TypeRef::Ptr(inner) => field_is_concrete(inner, struct_names),
        _ => false,
    }
}

pub(crate) fn resolve_struct_emit_mode(
    s: &crate::ir::StructDef,
    struct_names: &std::collections::HashSet<String>,
) -> StructEmitMode {
    let concrete = s
        .fields
        .iter()
        .filter(|f| field_is_concrete(&f.ty, struct_names))
        .count();
    if concrete == s.fields.len() {
        StructEmitMode::Full
    } else if concrete == 0 {
        StructEmitMode::Opaque
    } else {
        StructEmitMode::Partial
    }
}

fn has_unknown_named(
    ty: &TypeRef,
    struct_names: &std::collections::HashSet<String>,
) -> Option<String> {
    match ty {
        TypeRef::Named(s) => {
            if struct_names.contains(s) {
                None
            } else {
                Some(s.clone())
            }
        }
        TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Ptr(inner) => {
            has_unknown_named(inner, struct_names)
        }
        TypeRef::Result(ok, err) => {
            has_unknown_named(ok, struct_names).or_else(|| has_unknown_named(err, struct_names))
        }
        _ => None,
    }
}

pub fn generate_pxd(module: &crate::ir::Module, lib_name: &str) -> String {
    use crate::translator::to_cython_type;
    let mut out = String::new();

    out.push_str("# Auto-generated by rust2cython. Do not edit.\n\n");
    out.push_str("from libc.stddef cimport size_t\n\n");
    out.push_str(&format!("cdef extern from \"{}.h\":\n\n", lib_name));
    out.push_str("    void rust2cython_free_string(char* ptr)\n");
    out.push_str("    void rust2cython_free_string_array(char** ptr, size_t len)\n\n");

    // prepare set of struct names for type resolution
    let struct_names: std::collections::HashSet<String> =
        module.structs.iter().map(|s| s.name.clone()).collect();

    let struct_modes: std::collections::HashMap<String, StructEmitMode> = module
        .structs
        .iter()
        .map(|s| (s.name.clone(), resolve_struct_emit_mode(s, &struct_names)))
        .collect();

    // Structs first (inside extern block)
    for s in &module.structs {
        let mode = struct_modes[&s.name];
        if mode == StructEmitMode::Opaque {
            out.push_str(&format!("    ctypedef void* C{}_t\n\n", s.name));
            continue;
        }
        out.push_str(&format!(
            "    ctypedef struct C{} \"{}\":\n",
            s.name, s.name
        ));
        if s.fields.is_empty() {
            out.push_str("        pass\n");
        } else {
            let mut emitted_fields = 0usize;
            for f in &s.fields {
                if !field_is_concrete(&f.ty, &struct_names) {
                    let type_name = format!("{:?}", f.ty);
                    out.push_str(&format!(
                        "        # field `{}`: `{}` skipped — unresolved generic\n",
                        f.name, type_name
                    ));
                    continue;
                }
                let cty = match &f.ty {
                    TypeRef::Named(name) if struct_names.contains(name) => format!("C{}", name),
                    other => to_cython_type(other),
                };
                let (field_name, renamed) = cython_ident(&f.name);
                out.push_str(&format!("        {} {}", cty, field_name));
                if let Some(original) = renamed {
                    out.push_str(&format!(" # renamed from `{}` (Cython keyword)", original));
                }
                out.push('\n');
                emitted_fields += 1;
            }
            if emitted_fields == 0 {
                out.push_str("        pass\n");
            }
        }
        out.push('\n');
        if mode == StructEmitMode::Partial {
            eprintln!("[WARN] Struct `{}` emitted with incomplete fields — do not use sizeof({}_t) in C; treat as opaque or add a newtype.", s.name, s.name);
        }
    }

    // Functions
    for fn_def in &module.functions {
        // check for unknown named types used
        if let Some(name) = has_unknown_named(&fn_def.ret, &struct_names) {
            out.push_str(&format!(
                "    # WARNING: skipped {}, unknown type {}\n\n",
                fn_def.name, name
            ));
            continue;
        }
        if let Some(name) = fn_def
            .params
            .iter()
            .filter_map(|p| has_unknown_named(&p.ty, &struct_names))
            .next()
        {
            out.push_str(&format!(
                "    # WARNING: skipped {}, unknown type {}\n\n",
                fn_def.name, name
            ));
            continue;
        }

        let mut extra_params: Vec<String> = Vec::new();
        let ret = match &fn_def.ret {
            TypeRef::Str => "const char*".to_string(),
            TypeRef::Option(inner) => format!("const {}*", to_cython_type(inner)),
            TypeRef::Vec(inner) => {
                if **inner == TypeRef::Str {
                    extra_params.push("size_t* out_len".to_string());
                    "char**".to_string()
                } else {
                    let inner_ct = to_cython_type(inner);
                    extra_params.push(format!("{}* out, size_t out_len", inner_ct));
                    "void".to_string()
                }
            }
            TypeRef::Result(ok, _err) => {
                extra_params.push("char** error_out".to_string());
                to_cython_type(ok)
            }
            TypeRef::Named(s) if struct_modes.get(s) == Some(&StructEmitMode::Opaque) => {
                format!("C{}_t", s)
            }
            TypeRef::Named(s) => format!("C{}", s),
            TypeRef::Void => "void".to_string(),
            other => to_cython_type(other),
        };

        let mut params: Vec<String> = Vec::new();
        let mut renamed_params = Vec::new();
        for p in &fn_def.params {
            let (param_name, renamed) = cython_ident(&p.name);
            if let Some(original) = renamed {
                renamed_params.push(original);
            }
            match &p.ty {
                TypeRef::Str => params.push(format!("const char* {}", param_name)),
                TypeRef::Option(inner) => {
                    if **inner == TypeRef::Str {
                        params.push(format!("const char* {}", param_name))
                    } else {
                        params.push(format!("const {}* {}", to_cython_type(inner), param_name))
                    }
                }
                TypeRef::Vec(inner) => {
                    if **inner == TypeRef::Str {
                        params.push(format!(
                            "const char** {}, size_t {}_len",
                            param_name, param_name
                        ));
                    } else {
                        let inner_ct = to_cython_type(inner);
                        params.push(format!(
                            "const {}* {}, size_t {}_len",
                            inner_ct, param_name, param_name
                        ));
                    }
                }
                TypeRef::Named(s) if struct_modes.get(s) == Some(&StructEmitMode::Opaque) => {
                    params.push(format!("C{}_t {}", s, param_name))
                }
                TypeRef::Named(s) => params.push(format!("C{} {}", s, param_name)),
                other => params.push(format!("{} {}", to_cython_type(other), param_name)),
            }
        }

        for ep in extra_params {
            params.push(ep);
        }

        let params = params.join(", ");

        if matches!(&fn_def.ret, TypeRef::Option(_))
            || fn_def
                .params
                .iter()
                .any(|p| matches!(&p.ty, TypeRef::Option(_)))
        {
            out.push_str(
                "    # Note: Rust param/return must use *const <type> (not Option<T> directly)\n",
            );
        }

        out.push_str(&format!(
            "    {} c_{} \"{}\"({})",
            ret, fn_def.name, fn_def.name, params
        ));
        if !renamed_params.is_empty() {
            out.push_str(&format!(
                " # renamed from `{}` (Cython keyword)",
                renamed_params.join("`, `")
            ));
        }
        out.push('\n');
        out.push('\n');
    }

    let mut seen_enums = std::collections::HashSet::new();
    for e in &module.enums {
        if !seen_enums.insert(e.name.clone()) {
            continue;
        }
        // Rust enums are not ABI-stable by default. Keeping a declaration here also
        // makes `cython file.pxd` self-import the enum and report duplicate symbols.
        out.push_str(&format!("ctypedef enum {}:\n", e.name));
        for v in &e.variants {
            out.push_str(&format!("    {}\n", v.name));
        }
        out.push('\n');
    }

    out
}
