use crate::ir::TypeRef;

fn has_unknown_named(
    ty: &TypeRef,
    struct_names: &std::collections::HashSet<String>,
) -> Option<String> {
    match ty {
        TypeRef::Named(s) => {
            if struct_names.contains(s) {
                None
            } else {
                Some(s.clone())
            }
        }
        TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Ptr(inner) => {
            has_unknown_named(inner, struct_names)
        }
        TypeRef::Result(ok, err) => {
            has_unknown_named(ok, struct_names).or_else(|| has_unknown_named(err, struct_names))
        }
        _ => None,
    }
}

pub fn generate_pxd(module: &crate::ir::Module, lib_name: &str) -> String {
    use crate::translator::to_cython_type;
    let mut out = String::new();

    out.push_str("# Auto-generated by rust2cython. Do not edit.\n\n");
    out.push_str("from libc.stddef cimport size_t\n\n");
    out.push_str(&format!("cdef extern from \"{}.h\":\n\n", lib_name));

    // prepare set of struct names for type resolution
    let struct_names: std::collections::HashSet<String> =
        module.structs.iter().map(|s| s.name.clone()).collect();

    // Structs first (inside extern block)
    for s in &module.structs {
        out.push_str(&format!(
            "    ctypedef struct C{} \"{}\":\n",
            s.name, s.name
        ));
        if s.fields.is_empty() {
            out.push_str("        pass\n");
        } else {
            for f in &s.fields {
                let cty = to_cython_type(&f.ty);
                out.push_str(&format!("        {} {}\n", cty, f.name));
            }
        }
        out.push('\n');
    }

    // Functions
    for fn_def in &module.functions {
        // check for unknown named types used
        if let Some(name) = has_unknown_named(&fn_def.ret, &struct_names) {
            out.push_str(&format!(
                "    # WARNING: skipped {}, unknown type {}\n\n",
                fn_def.name, name
            ));
            continue;
        }
        if let Some(name) = fn_def
            .params
            .iter()
            .filter_map(|p| has_unknown_named(&p.ty, &struct_names))
            .next()
        {
            out.push_str(&format!(
                "    # WARNING: skipped {}, unknown type {}\n\n",
                fn_def.name, name
            ));
            continue;
        }

        let mut extra_params: Vec<String> = Vec::new();
        let ret = match &fn_def.ret {
            TypeRef::Str => "const char*".to_string(),
            TypeRef::Option(inner) => format!("const {}*", to_cython_type(inner)),
            TypeRef::Vec(inner) => {
                let inner_ct = to_cython_type(inner);
                extra_params.push(format!("{}* out, size_t out_len", inner_ct));
                "void".to_string()
            }
            TypeRef::Result(ok, _err) => {
                extra_params.push("char** error_out".to_string());
                to_cython_type(ok)
            }
            TypeRef::Named(s) => format!("C{}", s),
            TypeRef::Void => "void".to_string(),
            other => to_cython_type(other),
        };

        let mut params: Vec<String> = Vec::new();
        for p in &fn_def.params {
            match &p.ty {
                TypeRef::Str => params.push(format!("const char* {}", p.name)),
                TypeRef::Option(inner) => {
                    params.push(format!("const {}* {}", to_cython_type(inner), p.name))
                }
                TypeRef::Vec(inner) => {
                    let inner_ct = to_cython_type(inner);
                    params.push(format!(
                        "const {}* {}, size_t {}_len",
                        inner_ct, p.name, p.name
                    ));
                }
                TypeRef::Named(s) => params.push(format!("C{} {}", s, p.name)),
                other => params.push(format!("{} {}", to_cython_type(other), p.name)),
            }
        }

        for ep in extra_params {
            params.push(ep);
        }

        let params = params.join(", ");

        if matches!(&fn_def.ret, TypeRef::Option(_))
            || fn_def
                .params
                .iter()
                .any(|p| matches!(&p.ty, TypeRef::Option(_)))
        {
            out.push_str(
                "    # Note: Rust param/return must use *const <type> (not Option<T> directly)\n",
            );
        }

        out.push_str(&format!(
            "    {} c_{} \"{}\"({})\n",
            ret, fn_def.name, fn_def.name, params
        ));
        out.push('\n');
    }

    for e in &module.enums {
        out.push_str(&format!("cpdef enum {}:\n", e.name));
        for v in &e.variants {
            out.push_str(&format!("    {}\n", v.name));
        }
        out.push('\n');
    }

    out
}
