use crate::ir::TypeRef;

fn has_unknown_named(
    ty: &TypeRef,
    struct_names: &std::collections::HashSet<String>,
) -> Option<String> {
    match ty {
        TypeRef::Named(s) => {
            if struct_names.contains(s) {
                None
            } else {
                Some(s.clone())
            }
        }
        TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Ptr(inner) => {
            has_unknown_named(inner, struct_names)
        }
        TypeRef::Result(ok, err) => {
            has_unknown_named(ok, struct_names).or_else(|| has_unknown_named(err, struct_names))
        }
        _ => None,
    }
}

fn numpy_dtype_for(ty: &TypeRef) -> Option<&'static str> {
    use crate::ir::PrimKind::*;
    match ty {
        TypeRef::Primitive(p) => match p {
            I8 => Some("np.int8"),
            I16 => Some("np.int16"),
            I32 => Some("np.int32"),
            I64 => Some("np.int64"),
            U8 => Some("np.uint8"),
            U16 => Some("np.uint16"),
            U32 => Some("np.uint32"),
            U64 => Some("np.uint64"),
            F32 => Some("np.float32"),
            F64 => Some("np.float64"),
            Usize => Some("np.intp"),
            _ => None,
        },
        _ => None,
    }
}

fn module_uses_numpy(module: &crate::ir::Module) -> bool {
    for f in &module.functions {
        if let TypeRef::Vec(_) = &f.ret {
            return true;
        }
        for p in &f.params {
            if let TypeRef::Vec(_) = &p.ty {
                return true;
            }
        }
    }
    false
}

fn module_uses_result(module: &crate::ir::Module) -> bool {
    for f in &module.functions {
        if let TypeRef::Result(_, _) = &f.ret {
            return true;
        }
    }
    false
}

fn python_type_name(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Primitive(k) => {
            use crate::ir::PrimKind::*;
            match k {
                I8 | I16 | I32 | U8 | U16 | U32 | Usize => "int".to_string(),
                I64 | U64 => "int".to_string(),
                F32 | F64 => "float".to_string(),
                Bool => "bool".to_string(),
            }
        }
        TypeRef::Str => "str".to_string(),
        TypeRef::Vec(_) => "list".to_string(),
        TypeRef::Option(inner) => python_type_name(inner),
        TypeRef::Result(ok, _) => python_type_name(ok),
        TypeRef::Named(_) => "object".to_string(),
        TypeRef::Ptr(_) => "object".to_string(),
        TypeRef::Void => "None".to_string(),
    }
}

pub fn generate_pyx(module: &crate::ir::Module, pxd_name: &str) -> String {
    use crate::translator::{needs_wrapper, python_return_expr, to_cython_type};

    let mut out = String::new();
    out.push_str("# Auto-generated by rust2cython. Do not edit.\n\n");
    out.push_str(&format!("cimport {}\n", pxd_name));
    // only import numpy when needed
    if module_uses_numpy(module) {
        out.push_str("import numpy as np\n\n");
    } else {
        out.push('\n');
    }

    // import free when any Result<T,E> functions exist
    if module_uses_result(module) {
        out.push_str("from libc.stdlib cimport free\n\n");
    }

    // module-level warning if any function returns Str
    let mut has_str_return = false;
    for f in &module.functions {
        if let TypeRef::Str = f.ret {
            has_str_return = true;
            break;
        }
    }
    if has_str_return {
        out.push_str("# WARNING: String-returning functions require the Rust side to use\n");
        out.push_str("# CString::into_raw(). See README for memory safety notes.\n");
        out.push('\n');
    }

    let struct_names: std::collections::HashSet<String> =
        module.structs.iter().map(|s| s.name.clone()).collect();

    // Emit Python classes for each struct
    for s in &module.structs {
        out.push_str(&format!("cdef class {}:\n", s.name));
        out.push_str(&format!("    cdef {}.{} _c\n", pxd_name, s.name));
        // constructor signature with cython types
        let ctor_params = s
            .fields
            .iter()
            .map(|f| {
                let ctype = to_cython_type(&f.ty);
                format!("{} {}", ctype, f.name)
            })
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("    def __init__(self, {}):\n", ctor_params));
        if s.fields.is_empty() {
            out.push_str("        pass\n");
            out.push('\n');
        } else {
            for f in &s.fields {
                out.push_str(&format!("        self._c.{} = {}\n", f.name, f.name));
            }
            out.push('\n');
        }
    }

    for fn_def in &module.functions {
        // skip functions with unknown Named types
        if let Some(name) = has_unknown_named(&fn_def.ret, &struct_names) {
            out.push_str(&format!(
                "# WARNING: skipped {}, unknown type {}\n\n",
                fn_def.name, name
            ));
            continue;
        }
        if let Some(name) = fn_def
            .params
            .iter()
            .filter_map(|p| has_unknown_named(&p.ty, &struct_names))
            .next()
        {
            out.push_str(&format!(
                "# WARNING: skipped {}, unknown type {}\n\n",
                fn_def.name, name
            ));
            continue;
        }

        // determine whether this function needs a wrapper
        let mut any_needs = false;
        if needs_wrapper(&fn_def.ret) {
            any_needs = true;
        }
        for p in &fn_def.params {
            if needs_wrapper(&p.ty) {
                any_needs = true;
                break;
            }
        }

        // also generate wrappers for functions that take known struct types
        let takes_struct = fn_def.params.iter().any(|p| match &p.ty {
            TypeRef::Named(s) => struct_names.contains(s),
            _ => false,
        });

        if !any_needs && !takes_struct {
            out.push_str(&format!(
                "# {} is available directly as {}.{}\n\n",
                fn_def.name, pxd_name, fn_def.name
            ));
            continue;
        }

        // generate wrapper
        // build params signature with type hints for Named struct params
        let params_sig = fn_def
            .params
            .iter()
            .map(|p| match &p.ty {
                TypeRef::Named(s) if struct_names.contains(s) => format!("{}: {}", p.name, s),
                _ => p.name.clone(),
            })
            .collect::<Vec<_>>()
            .join(", ");

        // determine return hint per rules
        let ret_hint_opt = match &fn_def.ret {
            TypeRef::Primitive(k) => match k {
                crate::ir::PrimKind::F64 => Some("float".to_string()),
                crate::ir::PrimKind::I32 => Some("int".to_string()),
                crate::ir::PrimKind::Bool => Some("bool".to_string()),
                _ => None,
            },
            TypeRef::Named(s) if struct_names.contains(s) => Some(s.clone()),
            _ => None,
        };

        if let Some(hint) = &ret_hint_opt {
            out.push_str(&format!(
                "def {}({}) -> {}:\n",
                fn_def.name, params_sig, hint
            ));
        } else {
            let py_ret = python_type_name(&fn_def.ret);
            out.push_str(&format!(
                "def {}({}) -> {}:\n",
                fn_def.name, params_sig, py_ret
            ));
        }

        // if this function returns a string, add explanatory comment
        if let TypeRef::Str = fn_def.ret {
            out.push_str(
                "    # Note: Rust must return this as CString (std::ffi::CString::into_raw)\n",
            );
        }
        // if this function uses Option in params/return, add explanatory comment
        let uses_option = matches!(&fn_def.ret, TypeRef::Option(_))
            || fn_def
                .params
                .iter()
                .any(|p| matches!(&p.ty, TypeRef::Option(_)));
        if uses_option {
            out.push_str(
                "    # Note: Rust param/return must use *const <type> (not Option<T> directly)\n",
            );
        }
        if let Some(d) = &fn_def.doc {
            out.push_str(&format!(
                "    \"\"\"{}\n    \"\"\"\n",
                d.replace('\n', "\n    ")
            ));
        }

        // conversions and call args; replace Named struct params with ._c
        let mut call_args = Vec::new();
        for p in &fn_def.params {
            match &p.ty {
                TypeRef::Named(s) if struct_names.contains(s) => {
                    call_args.push(format!("{}.{}", p.name, "_c"));
                }
                TypeRef::Str => {
                    out.push_str(&format!(
                        "    cdef bytes _{}_b = {}.encode('utf-8')\n",
                        p.name, p.name
                    ));
                    call_args.push(format!("_{}_b", p.name));
                }
                TypeRef::Vec(inner) => {
                    if let Some(dtype) = numpy_dtype_for(inner) {
                        let inner_c = to_cython_type(inner);
                        out.push_str(&format!(
                            "    cdef {}[::1] _{}_mv = np.asarray({}, dtype={})\n",
                            inner_c, p.name, p.name, dtype
                        ));
                        out.push_str("    # pass pointer to data start\n");
                        call_args.push(format!("&_{0}_mv[0]", p.name));
                    } else {
                        // non-numeric vector -> pass list directly
                        call_args.push(p.name.clone());
                    }
                }
                TypeRef::Option(inner) => {
                    // Option<T> params are passed as const <type>* per convention
                        let inner_cty = to_cython_type(inner);
                    out.push_str(&format!("    cdef {} _{}_val\n", inner_cty, p.name));
                    out.push_str(&format!("    cdef const {}* _{}_ptr\n", inner_cty, p.name));
                    out.push_str(&format!("    if {} is None:\n", p.name));
                    out.push_str(&format!("        _{}_ptr = NULL\n", p.name));
                    out.push_str("    else:\n");
                    out.push_str(&format!("        _{}_val = {}\n", p.name, p.name));
                    out.push_str(&format!("        _{}_ptr = &_{0}_val\n", p.name));
                    call_args.push(format!("_{}_ptr", p.name));
                }
                _ => {
                    call_args.push(p.name.clone());
                }
            }
        }

        // handle string returns specially: declare const char* and decode
        // handle Result<T,E> return convention
        let is_result = matches!(&fn_def.ret, TypeRef::Result(_, _));
        if is_result {
            // prepare error out param
            out.push_str("    # Note: Rust must use CString::into_raw() for the error string.\n");
            out.push_str(
                "    # The generated wrapper does NOT free the error string (memory leak risk).\n",
            );
            out.push_str(
                "    # See README for how to implement free_rust_string() in your Rust lib.\n",
            );
            out.push_str("    cdef char* _err = NULL\n");
        }

        if let TypeRef::Str = fn_def.ret {
            out.push_str(&format!(
                "    cdef const char* _result = {}.{}({})\n",
                pxd_name,
                fn_def.name,
                call_args.join(", ")
            ));
            out.push_str("    return _result.decode('utf-8')\n\n");
        } else if let TypeRef::Named(s) = &fn_def.ret {
            if struct_names.contains(s) {
                // return a struct: call and wrap into Python object
                let mut call_args_str = call_args.join(", ");
                if is_result {
                    if call_args_str.is_empty() {
                        call_args_str = "&_err".to_string();
                    } else {
                        call_args_str = format!("{}, &_err", call_args_str);
                    }
                }
                out.push_str(&format!(
                    "    cdef {}.{} _result = {}.{}({})\n",
                    pxd_name, s, pxd_name, fn_def.name, call_args_str
                ));
                out.push_str(&format!("    out = {}.__new__({})\n", s, s));
                out.push_str("    out._c = _result\n");
                out.push_str("    return out\n\n");
            } else {
                // unknown Named handled earlier, but fallback
                let cy_ret = to_cython_type(&fn_def.ret);
                let call_args_str = call_args.join(", ");
                out.push_str(&format!(
                    "    cdef {} _result = {}.{}({})\n",
                    cy_ret, pxd_name, fn_def.name, call_args_str
                ));
                let ret_expr = python_return_expr(&fn_def.ret, "_result");
                out.push_str(&format!("    return {}\n\n", ret_expr));
            }
        } else {
            // Option return handling
            if let TypeRef::Option(inner) = &fn_def.ret {
                let inner_cty = to_cython_type(inner);
                match &**inner {
                    TypeRef::Named(s) if struct_names.contains(s) => {
                        out.push_str(&format!(
                            "    cdef const {}.{}* _result = {}.{}({})\n",
                            pxd_name,
                            s,
                            pxd_name,
                            fn_def.name,
                            call_args.join(", ")
                        ));
                        out.push_str("    if _result is NULL:\n");
                        out.push_str("        return None\n");
                        out.push_str(&format!("    out = {}.__new__({})\n", s, s));
                        out.push_str("    out._c = _result[0]\n");
                        out.push_str("    return out\n\n");
                    }
                    _ => {
                        out.push_str(&format!(
                            "    cdef const {0}* _result = {1}.{2}({3})\n",
                            inner_cty,
                            pxd_name,
                            fn_def.name,
                            call_args.join(", ")
                        ));
                        out.push_str("    return None if _result is NULL else _result[0]\n\n");
                    }
                }
            } else {
                let cy_ret = to_cython_type(&fn_def.ret);
                let call_args_str = call_args.join(", ");
                if is_result {
                    // for Result<T,E>, call with &_err as last arg and check error
                    out.push_str(&format!(
                        "    cdef {0} _result = {1}.{2}({3}, &_err)\n",
                        cy_ret, pxd_name, fn_def.name, call_args_str
                    ));
                    out.push_str("    if _err is not NULL:\n");
                    out.push_str("        msg = _err.decode('utf-8')\n");
                    out.push_str("        raise RuntimeError(msg)\n");
                    // return the Ok value (convert if needed)
                    if let TypeRef::Result(ok_ty, _err_ty) = &fn_def.ret {
                        let ret_expr = python_return_expr(ok_ty, "_result");
                        out.push_str(&format!("    return {}\n\n", ret_expr));
                    } else {
                        out.push_str("    return _result\n\n");
                    }
                } else {
                    out.push_str(&format!(
                        "    cdef {} _result = {}.{}({})\n",
                        cy_ret, pxd_name, fn_def.name, call_args_str
                    ));
                    let ret_expr = python_return_expr(&fn_def.ret, "_result");
                    out.push_str(&format!("    return {}\n\n", ret_expr));
                }
            }
        }
    }

    out
}
