use crate::ir::TypeRef;

fn numpy_dtype_for(ty: &TypeRef) -> Option<&'static str> {
    use crate::ir::PrimKind::*;
    match ty {
        TypeRef::Primitive(p) => match p {
            I8 => Some("np.int8"),
            I16 => Some("np.int16"),
            I32 => Some("np.int32"),
            I64 => Some("np.int64"),
            U8 => Some("np.uint8"),
            U16 => Some("np.uint16"),
            U32 => Some("np.uint32"),
            U64 => Some("np.uint64"),
            F32 => Some("np.float32"),
            F64 => Some("np.float64"),
            Usize => Some("np.intp"),
            _ => None,
        },
        _ => None,
    }
}

pub fn generate_pyx(module: &crate::ir::Module, name: &str) -> String {
    use crate::translator::to_cython_type;

    let mut out = String::new();
    out.push_str("# Auto-generated by rust2cython. Do not edit.\n\n");
    out.push_str("from libc.stddef cimport size_t\n");
    out.push_str("from libc.stdlib cimport free, malloc\n");
    out.push_str("import numpy as np\n\n");

    // extern block (mirror pxd)
    out.push_str(&format!("cdef extern from \"{}.h\":\n\n", name));
    out.push_str("    void rust2cython_free_string(char* ptr)\n");
    out.push_str("    void rust2cython_free_string_array(char** ptr, size_t len)\n\n");

    // structs.  A Rust struct containing Rust-owned fields (for example String)
    // is opaque at the FFI boundary; declaring its layout in Cython is invalid.
    let struct_names: std::collections::HashSet<String> =
        module.structs.iter().map(|s| s.name.clone()).collect();
    let struct_modes: std::collections::HashMap<String, crate::pxd_gen::StructEmitMode> = module
        .structs
        .iter()
        .map(|s| {
            (
                s.name.clone(),
                crate::pxd_gen::resolve_struct_emit_mode(s, &struct_names),
            )
        })
        .collect();
    for s in &module.structs {
        if struct_modes[&s.name] == crate::pxd_gen::StructEmitMode::Opaque {
            continue;
        }
        out.push_str(&format!(
            "    ctypedef struct C{} \"{}\":\n",
            s.name, s.name
        ));
        if s.fields.is_empty() {
            out.push_str("        pass\n");
        } else {
            let mut emitted_fields = 0usize;
            for f in &s.fields {
                if !crate::pxd_gen::field_is_concrete(&f.ty, &struct_names) {
                    out.push_str(&format!(
                        "        # field `{}` skipped — unresolved generic\n",
                        f.name
                    ));
                    continue;
                }
                let cty = match &f.ty {
                    TypeRef::Named(name) => format!("C{}", name),
                    other => to_cython_type(other),
                };
                let (field_name, renamed) = crate::pxd_gen::cython_ident(&f.name);
                out.push_str(&format!("        {} {}", cty, field_name));
                if let Some(original) = renamed {
                    out.push_str(&format!(" # renamed from `{}` (Cython keyword)", original));
                }
                out.push('\n');
                emitted_fields += 1;
            }
            if emitted_fields == 0 {
                out.push_str("        pass\n");
            }
        }
        out.push('\n');
    }

    // functions (aliased)
    for fn_def in &module.functions {
        if matches!(fn_def.ret, TypeRef::Tuple) {
            continue;
        }
        // prepare params in pxd style
        let mut params = Vec::new();
        let mut unknown_named = None;
        for p in &fn_def.params {
            match &p.ty {
                TypeRef::Str => params.push(format!("const char* {}", p.name)),
                TypeRef::Option(inner) => match &**inner {
                    TypeRef::Primitive(_) => {
                        params.push(format!("const {}* {}", to_cython_type(inner), p.name))
                    }
                    TypeRef::Str => params.push(format!("const char* {}", p.name)),
                    _ => {
                        unknown_named = Some(p.name.clone());
                    }
                },
                TypeRef::Vec(inner) => match &**inner {
                    TypeRef::Primitive(_) => params.push(format!(
                        "const {}* {}, size_t {}_len",
                        to_cython_type(inner),
                        p.name,
                        p.name
                    )),
                    TypeRef::Str => {
                        params.push(format!("const char** {}, size_t {}_len", p.name, p.name))
                    }
                    _ => {
                        unknown_named = Some(p.name.clone());
                    }
                },
                TypeRef::Named(sn)
                    if struct_modes.get(sn) == Some(&crate::pxd_gen::StructEmitMode::Opaque) =>
                {
                    params.push(format!("void* {}", p.name))
                }
                TypeRef::Ptr(inner, _) if matches!(&**inner, TypeRef::Named(s) if struct_modes.get(s) == Some(&crate::pxd_gen::StructEmitMode::Opaque)) => {
                    if let TypeRef::Named(_s) = &**inner {
                        params.push(format!("void* {}", p.name))
                    }
                }
                TypeRef::Named(sn) => params.push(format!("C{} {}", sn, p.name)),
                other => params.push(format!("{} {}", to_cython_type(other), p.name)),
            }
        }
        if unknown_named.is_some() {
            out.push_str(&format!(
                "    # WARNING: skipped {}, unknown named param\n\n",
                fn_def.name
            ));
            continue;
        }

        // return handling
        let mut extra = Vec::new();
        let ret = match &fn_def.ret {
            TypeRef::Str => "const char*".to_string(),
            TypeRef::Option(inner) => {
                if **inner == TypeRef::Str {
                    "const char*".to_string()
                } else if let TypeRef::Named(name) = &**inner {
                    format!("const C{}*", name)
                } else {
                    format!("const {}*", to_cython_type(inner))
                }
            }
            TypeRef::Vec(inner) => {
                if **inner == TypeRef::Str {
                    extra.push("size_t* out_len".to_string());
                    "char**".to_string()
                } else {
                    extra.push(format!("{}* out", to_cython_type(inner)));
                    extra.push("size_t out_len".to_string());
                    "void".to_string()
                }
            }
            TypeRef::Result(ok, _err) => {
                extra.push("char** error_out".to_string());
                to_cython_type(ok)
            }
            TypeRef::Named(name)
                if struct_modes.get(name) == Some(&crate::pxd_gen::StructEmitMode::Opaque) =>
            {
                "void*".to_string()
            }
            TypeRef::Ptr(inner, _) if matches!(&**inner, TypeRef::Named(s) if struct_modes.get(s) == Some(&crate::pxd_gen::StructEmitMode::Opaque)) => {
                if let TypeRef::Named(_s) = &**inner {
                    "void*".to_string()
                } else {
                    unreachable!()
                }
            }
            TypeRef::Named(name) => format!("C{}", name),
            other => to_cython_type(other),
        };

        for e in extra {
            params.push(e);
        }
        let params = params.join(", ");
        out.push_str(&format!(
            "    {} c_{} \"{}\"({})\n\n",
            ret, fn_def.name, fn_def.name, params
        ));
    }

    out.push('\n');

    // cdef classes for structs
    for s in &module.structs {
        out.push_str(&format!("cdef class {}:\n", s.name));
        if struct_modes[&s.name] == crate::pxd_gen::StructEmitMode::Opaque {
            out.push_str("    cdef void* _ptr\n");
            out.push_str("    def __dealloc__(self):\n        pass\n\n");
            continue;
        }
        out.push_str(&format!("    cdef C{} _c\n", s.name));
        // constructor
        let ctor_params = s
            .fields
            .iter()
            .filter(|f| crate::pxd_gen::field_is_concrete(&f.ty, &struct_names))
            .map(|f| {
                let cty = match &f.ty {
                    TypeRef::Named(name) if struct_names.contains(name) => name.clone(),
                    other => to_cython_type(other),
                };
                let (param_name, _) = crate::pxd_gen::cython_ident(&f.name);
                format!("{} {}", cty, param_name)
            })
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("    def __init__(self, {}):\n", ctor_params));
        if !s
            .fields
            .iter()
            .any(|f| crate::pxd_gen::field_is_concrete(&f.ty, &struct_names))
        {
            out.push_str("        pass\n\n");
        } else {
            for f in &s.fields {
                if !crate::pxd_gen::field_is_concrete(&f.ty, &struct_names) {
                    continue;
                }
                let (field_name, _) = crate::pxd_gen::cython_ident(&f.name);
                out.push_str(&format!("        self._c.{0} = {0}\n", field_name));
            }
            out.push('\n');
        }
    }

    // function wrappers
    for fn_def in &module.functions {
        // skip unknown named types
        let has_unknown = fn_def.params.iter().any(
            |p| matches!(&p.ty, TypeRef::Named(n) if module.structs.iter().all(|s| &s.name != n)),
        );
        if has_unknown {
            out.push_str(&format!(
                "# WARNING: skipped {}, unknown named\n\n",
                fn_def.name
            ));
            continue;
        }

        // build signature
        let params_sig = fn_def
            .params
            .iter()
            .map(|p| {
                let (param_name, _) = crate::pxd_gen::cython_ident(&p.name);
                match &p.ty {
                TypeRef::Named(sn) => format!("{}: {}", param_name, sn),
                TypeRef::Ptr(inner, _) if matches!(&**inner, TypeRef::Named(s) if struct_modes.get(s) == Some(&crate::pxd_gen::StructEmitMode::Opaque)) => {
                    if let TypeRef::Named(s) = &**inner { format!("{}: {}", param_name, s) } else { unreachable!() }
                }
                TypeRef::Ptr(inner, _) if numpy_dtype_for(inner).is_some() => format!("{}[::1] {}", to_cython_type(inner), param_name),
                    _ => param_name,
                }
            })
            .collect::<Vec<_>>()
            .join(", ");

        let ret_hint = match &fn_def.ret {
            TypeRef::Primitive(k) => match k {
                crate::ir::PrimKind::F64 => "float".to_string(),
                crate::ir::PrimKind::I32 => "int".to_string(),
                crate::ir::PrimKind::Bool => "bool".to_string(),
                _ => "".to_string(),
            },
            TypeRef::Named(s) => s.clone(),
            _ => "".to_string(),
        };

        if ret_hint.is_empty() {
            out.push_str(&format!("def {}({}):\n", fn_def.name, params_sig));
        } else {
            out.push_str(&format!(
                "def {}({}) -> {}:\n",
                fn_def.name, params_sig, ret_hint
            ));
        }

        // body generation
        // prepare call args and any pre-conversions
        let mut pre = Vec::new();
        let mut call_args = Vec::new();
        let mut created_mv: std::collections::HashSet<String> = std::collections::HashSet::new();

        for p in &fn_def.params {
            match &p.ty {
                TypeRef::Named(sn) => {
                    pre.push(format!("    cdef C{} _{}_c = {}._c", sn, p.name, p.name));
                    call_args.push(format!("_{}_c", p.name));
                }
                TypeRef::Ptr(inner, _) if matches!(&**inner, TypeRef::Named(s) if struct_modes.get(s) == Some(&crate::pxd_gen::StructEmitMode::Opaque)) =>
                {
                    call_args.push(format!("{}._ptr", p.name));
                }
                TypeRef::Ptr(inner, _) if numpy_dtype_for(inner).is_some() => {
                    call_args.push(format!("&{}[0]", p.name));
                }
                TypeRef::Str => {
                    // if it is Option<String>, it can be None
                    pre.push(format!(
                        "    cdef bytes _{0}_b = {0}.encode('utf-8') if {0} is not None else None",
                        p.name
                    ));
                    call_args.push(format!("_{0}_b if {0} is not None else NULL", p.name));
                }
                TypeRef::Vec(inner) => {
                    if **inner == TypeRef::Str {
                        pre.push(format!(
                            "    cdef list _{}_bytes = [s.encode('utf-8') for s in {}]",
                            p.name, p.name
                        ));
                        pre.push(format!(
                            "    cdef const char** _{}_arr = <const char**>malloc(len(_{}_bytes) * sizeof(char*)) if len(_{}_bytes) > 0 else NULL",
                            p.name, p.name, p.name
                        ));
                        pre.push(format!("    cdef size_t _{}_idx", p.name));
                        pre.push(format!(
                            "    for _{0}_idx, _{0}_b in enumerate(_{0}_bytes):\n        _{0}_arr[_{0}_idx] = _{0}_b",
                            p.name
                        ));
                        call_args.push(format!("_{}_arr", p.name));
                        call_args.push(format!("len(_{}_bytes)", p.name));
                    } else if let Some(dtype) = numpy_dtype_for(inner) {
                        let inner_ct = to_cython_type(inner);
                        // avoid duplicate memview declarations
                        if !created_mv.contains(&p.name) {
                            pre.push(format!(
                                "    cdef {0}[::1] _{1}_mv = np.asarray({1}, dtype={2})",
                                inner_ct, p.name, dtype
                            ));
                            created_mv.insert(p.name.clone());
                        }
                        call_args.push(format!("&_{0}_mv[0]", p.name));
                        call_args.push(format!("len(_{0}_mv)", p.name));
                    } else {
                        call_args.push(p.name.clone());
                    }
                }
                TypeRef::Option(inner) => {
                    let inner_ct = to_cython_type(inner);
                    pre.push(format!(
                        "    cdef {0} _{1}_val\n    cdef const {0}* _{1}_ptr",
                        inner_ct, p.name
                    ));
                    pre.push(format!("    if {0} is None:\n        _{0}_ptr = NULL\n    else:\n        _{0}_val = {0}\n        _{0}_ptr = &_{0}_val", p.name));
                    call_args.push(format!("_{0}_ptr", p.name));
                }
                _other => {
                    call_args.push(p.name.clone());
                }
            }
        }

        for line in pre {
            out.push_str(&format!("{}\n", line));
        }

        // handle return cases
        let mut cleanup = String::new();
        for p in &fn_def.params {
            if let TypeRef::Vec(inner) = &p.ty {
                if **inner == TypeRef::Str {
                    cleanup.push_str(&format!(
                        "    if _{}_arr is not NULL:\n        free(_{}_arr)\n",
                        p.name, p.name
                    ));
                }
            }
        }

        match &fn_def.ret {
            TypeRef::Primitive(_) => {
                let cy_ret = to_cython_type(&fn_def.ret);
                out.push_str(&format!(
                    "    cdef {} _result = c_{}({})\n",
                    cy_ret,
                    fn_def.name,
                    call_args.join(", ")
                ));
                out.push_str(&cleanup);
                out.push_str("    return _result\n\n");
            }
            TypeRef::Vec(inner) => {
                if **inner == TypeRef::Str {
                    out.push_str("    cdef size_t _out_len = 0\n");
                    let mut call = call_args.clone();
                    call.push("&_out_len".to_string());
                    out.push_str(&format!(
                        "    cdef char** _result = c_{}({})\n",
                        fn_def.name,
                        call.join(", ")
                    ));
                    out.push_str("    cdef list _ret_list = []\n");
                    out.push_str("    cdef size_t _i\n");
                    out.push_str(&cleanup);
                    out.push_str("    try:\n");
                    out.push_str("        if _result is not NULL:\n");
                    out.push_str("            for _i in range(_out_len):\n");
                    out.push_str(
                        "                _ret_list.append(_result[_i].decode(\'utf-8\'))\n",
                    );
                    out.push_str("    finally:\n");
                    out.push_str("        rust2cython_free_string_array(_result, _out_len)\n");
                    out.push_str("    return _ret_list\n\n");
                } else if let Some(_dtype) = numpy_dtype_for(inner) {
                    // find first vec param name
                    let first_vec = fn_def
                        .params
                        .iter()
                        .find(|p| matches!(&p.ty, TypeRef::Vec(_)))
                        .map(|p| p.name.clone());
                    if let Some(fname) = &first_vec {
                        let len_expr = format!("len(_{}_mv)", fname);
                        out.push_str(&format!(
                            "    cdef {0}[::1] _out = np.zeros({1}, dtype=np.float64)\n",
                            to_cython_type(inner),
                            len_expr
                        ));
                        // assemble call args: need to include other args then out pointer
                        let mut call = call_args.clone();
                        call.push("&_out[0]".to_string());
                        call.push("len(_out)".to_string());
                        out.push_str(&format!("    c_{}({})\n", fn_def.name, call.join(", ")));
                        out.push_str(&cleanup);
                        out.push_str("    return np.asarray(_out)\n\n");
                    } else {
                        let rust_type = format!("{:?}", fn_def.ret);
                        eprintln!("[WARN] fn `{}` — return type `{}` has no FFI mapping. Emitting NotImplementedError stub in .pyx.", fn_def.name, rust_type);
                        out.push_str(&format!(
                            "    # return type `{}` has no Cython mapping — not implemented\n",
                            rust_type
                        ));
                        out.push_str(&format!("    raise NotImplementedError(\"{}: return type `{}` has no Cython FFI mapping\")\n\n", fn_def.name, rust_type));
                    }
                } else {
                    let rust_type = format!("{:?}", fn_def.ret);
                    eprintln!("[WARN] fn `{}` — return type `{}` has no FFI mapping. Emitting NotImplementedError stub in .pyx.", fn_def.name, rust_type);
                    out.push_str(&format!(
                        "    # return type `{}` has no Cython mapping — not implemented\n",
                        rust_type
                    ));
                    out.push_str(&format!("    raise NotImplementedError(\"{}: return type `{}` has no Cython FFI mapping\")\n\n", fn_def.name, rust_type));
                }
            }
            TypeRef::Named(s) => {
                out.push_str(&format!(
                    "    cdef C{0} _result = c_{1}({2})\n",
                    s,
                    fn_def.name,
                    call_args.join(", ")
                ));
                out.push_str(&cleanup);
                out.push_str(&format!(
                    "    out = {0}.__new__({0})\n    out._c = _result\n    return out\n\n",
                    s
                ));
            }
            TypeRef::Ptr(inner, _) => {
                if let TypeRef::Named(s) = &**inner {
                    if struct_modes.get(s) == Some(&crate::pxd_gen::StructEmitMode::Opaque) {
                        out.push_str(&format!(
                            "    cdef void* _result = c_{1}({2})\n    cdef {0} out\n",
                            s,
                            fn_def.name,
                            call_args.join(", ")
                        ));
                        out.push_str("    if _result is NULL:\n        return None\n");
                        out.push_str(&format!("    out = {0}.__new__({0})\n    out._ptr = _result\n    return out\n\n", s));
                    } else {
                        out.push_str("    raise NotImplementedError(\"raw pointer return requires an opaque struct\")\n\n");
                    }
                } else {
                    out.push_str("    raise NotImplementedError(\"raw pointer return requires an opaque struct\")\n\n");
                }
            }
            TypeRef::Tuple => {
                out.push_str("    raise NotImplementedError(\"tuple return has no stable C ABI; use a #[repr(C)] newtype struct\")\n\n");
            }
            TypeRef::Option(inner) => match &**inner {
                TypeRef::Named(s) => {
                    out.push_str(&format!(
                        "    cdef const C{0}* _result = c_{1}({2})\n",
                        s,
                        fn_def.name,
                        call_args.join(", ")
                    ));
                    out.push_str(&cleanup);
                    out.push_str(&format!("    if _result is NULL:\n        return None\n    out = {0}.__new__({0})\n    out._c = _result[0]\n    return out\n\n", s));
                }
                TypeRef::Str => {
                    out.push_str("    # Memory automatically managed — rust2cython_free_string called on return.\n");
                    out.push_str(&format!(
                        "    cdef char* _result = c_{0}({1})\n",
                        fn_def.name,
                        call_args.join(", ")
                    ));
                    out.push_str(&cleanup);
                    out.push_str("    if _result is NULL:\n        return None\n    try:\n");
                    out.push_str("        py_str = _result.decode(\'utf-8\')\n");
                    out.push_str("    finally:\n");
                    out.push_str("        rust2cython_free_string(_result)\n");
                    out.push_str("    return py_str\n\n");
                }
                _ => {
                    out.push_str(&format!(
                        "    cdef const {0}* _result = c_{1}({2})\n",
                        to_cython_type(inner),
                        fn_def.name,
                        call_args.join(", ")
                    ));
                    out.push_str(&cleanup);
                    out.push_str("    return None if _result is NULL else _result[0]\n\n");
                }
            },
            TypeRef::Result(ok, _err) => {
                let ok_ct = to_cython_type(ok);
                out.push_str(&format!(
                    "    cdef char* _err = NULL\n    cdef {0} _result = c_{1}({2}, &_err)\n",
                    ok_ct,
                    fn_def.name,
                    call_args.join(", ")
                ));
                out.push_str(&cleanup);
                out.push_str("    if _err is not NULL:\n        msg = _err.decode(\'utf-8\')\n        free(_err)\n        raise RuntimeError(msg)\n");
                out.push_str("    return _result\n\n");
            }
            TypeRef::Str => {
                out.push_str("    # Memory automatically managed — rust2cython_free_string called on return.\n");
                out.push_str(&format!(
                    "    cdef char* _result = c_{0}({1})\n",
                    fn_def.name,
                    call_args.join(", ")
                ));
                out.push_str(&cleanup);
                out.push_str("    try:\n");
                out.push_str("        py_str = _result.decode(\'utf-8\')\n");
                out.push_str("    finally:\n");
                out.push_str("        rust2cython_free_string(_result)\n");
                out.push_str("    return py_str\n\n");
            }
            TypeRef::Void => {
                out.push_str(&format!(
                    "    c_{}({})\n",
                    fn_def.name,
                    call_args.join(", ")
                ));
                out.push_str(&cleanup);
                out.push_str("    return\n\n");
            }
        }
    }

    out
}
