pub fn generate_setup_files(lib_name: &str, rust_source: &str) -> (String, String) {
    let setup = format!(
        r###"from setuptools import setup
from Cython.Build import cythonize
from setuptools.extension import Extension
import numpy as np

extensions = [
    Extension(
        name="{name}",
        sources=["{name}.pyx"],
        libraries=["{name}"],
        library_dirs=["."],
        include_dirs=[np.get_include()],
        extra_compile_args=["-O3"],
    )
]

setup(
    name="{name}",
    ext_modules=cythonize(extensions, language_level="3"),
)
"###,
        name = lib_name
    );

    let pyproject = format!(
        r###"[build-system]
requires = ["setuptools", "cython", "numpy"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "{name}"
version = "0.1.0"
description = "Python bindings for {name}, generated by rust2cython."
requires-python = ">=3.8"
dependencies = ["numpy"]

[tool.rust2cython]
source = "{src}"
generated_by = "rust2cython"
"###,
        name = lib_name,
        src = rust_source
    );

    (setup, pyproject)
}

pub fn generate_build_instructions(lib_name: &str) -> String {
    format!(
        r###"#!/bin/sh
# Build the Rust library first
cargo build --release

# Copy the compiled library to the current directory
# (adjust the extension for your OS: .so on Linux, .dylib on macOS, .dll on Windows)
cp target/release/lib{lib}.so ./{lib}.so   # Linux
# cp target/release/lib{lib}.dylib ./{lib}.so  # macOS

# Copy the generated shim into your src/ directory
# cp {lib}_ffi.rs path/to/your/crate/src/
# Then add this line to your lib.rs:
# mod {lib}_ffi;

# Build and install the Python extension
pip install cython numpy
python setup.py build_ext --inplace

# Test the import
python -c "import {lib}; print('{lib} imported successfully')"
"###,
        lib = lib_name
    )
}
