pub fn generate_setup_files(
    lib_name: &str,
    _rust_source: &str,
    platform: &str,
    version: &str,
) -> (String, String) {
    let rpath_detection = match platform {
        "macos" => "rpath_arg = \"-Wl,-rpath,@loader_path\"",
        "linux" => "rpath_arg = \"-Wl,-rpath,$ORIGIN\"",
        _ => r###"import sys
# Detect platform for rpath
if sys.platform == "darwin":
    rpath_arg = "-Wl,-rpath,@loader_path"
else:
    rpath_arg = "-Wl,-rpath,$ORIGIN"
"###,
    };

    let setup = format!(
        r###"from setuptools import setup
from Cython.Build import cythonize
from setuptools.extension import Extension
import numpy as np

{rpath_detection}

extensions = [
    Extension(
        name="{name}",
        sources=["{name}.pyx"],
        libraries=["{name}"],
        library_dirs=["."],
        include_dirs=[np.get_include()],
        extra_compile_args=["-O3"],
        extra_link_args=[rpath_arg],
    )
]

setup(
    name="{name}",
    ext_modules=cythonize(extensions, language_level="3"),
)
"###,
        name = lib_name
    );

    let pyproject = format!(
        r###"[build-system]
requires = ["setuptools", "cython", "numpy"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "{name}"
version = "{version}"
description = "Python bindings for {name}, generated by rust2cython."
requires-python = ">=3.8"
dependencies = ["numpy"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["*.so", "*.dylib", "*.h", "*.pxd"]

[tool.rust2cython]
generated_by = "rust2cython"
"###,
        name = lib_name,
        version = version
    );

    (setup, pyproject)
}

pub fn generate_requirements() -> String {
    "cython\nnumpy\nsetuptools\nbuild\n".to_string()
}

pub fn generate_dev_requirements() -> String {
    r###"# requirements-dev.txt — tools for repairing wheels
# On Linux: auditwheel
# On macOS: delocate
auditwheel
delocate
"###
    .to_string()
}

pub fn generate_build_instructions(lib_name: &str, platform: &str, emit_wheel: bool) -> String {
    let name = lib_name;
    let os_detection = match platform {
        "macos" => r###"OS_NAME="Darwin"
SO_NAME="lib${LIB_NAME}.dylib""###,
        "linux" => r###"OS_NAME="Linux"
SO_NAME="lib${LIB_NAME}.so""###,
        _ => r###"OS_NAME=$(uname -s)
if [ "$OS_NAME" = "Darwin" ]; then
    SO_NAME="lib${LIB_NAME}.dylib"
else
    SO_NAME="lib${LIB_NAME}.so"
fi"###,
    };

    let start = format!(
        r###"#!/bin/sh
set -e

LIB_NAME="{name}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CRATE_ROOT="$(dirname "$SCRIPT_DIR")"

{os_detection}

echo "NOTE: rust2cython patched your src/lib.rs and added"
echo "  src/{name}_ffi.rs — do not edit these manually."
echo "  Rerun rust2cython to regenerate."
echo ""

echo "[1/5] Building Rust crate..."
cd "$CRATE_ROOT"
cargo build --release

SO_SRC="$CRATE_ROOT/target/release/$SO_NAME"
    if [ ! -f "$SO_SRC" ]; then
        echo "ERROR: $SO_SRC not found. Did cargo build succeed?"
        exit 1
    fi

    echo "[2/5] Copying shared library..."
    cp "$SO_SRC" "$SCRIPT_DIR/"

    if [ ! -f "$SCRIPT_DIR/{name}.h" ]; then
        echo "ERROR: {name}.h not found in $SCRIPT_DIR"
        echo "Rerun: rust2cython src/lib.rs -o <output_dir>/ -n {name}"
        exit 1
    fi

    echo "[3/5] Installing Python dependencies..."
    cd "$SCRIPT_DIR"
    pip3 install -r requirements.txt

    RPATH_FIX_PRE_VAR=""
    RPATH_FIX_POST_VAR=""
    if [ "$OS_NAME" = "Darwin" ]; then
        if ! command -v install_name_tool >/dev/null 2>&1; then
            echo "WARNING: install_name_tool not found. Dynamic library may not be portable. Install with: brew install cctools"
        else
            RPATH_FIX_POST_VAR="install_name_tool -add_rpath @loader_path $SO_EXT"
        fi
    else
        if ! command -v patchelf >/dev/null 2>&1; then
            echo "WARNING: patchelf not found. Dynamic library may not be portable. Install with: sudo apt install patchelf"
        else
            RPATH_FIX_PRE_VAR="LD_LIBRARY_PATH=\"$SCRIPT_DIR\""
            RPATH_FIX_POST_VAR="patchelf --set-rpath \"\$ORIGIN\" $SO_EXT"
        fi
    fi

    echo "[4/5] Building Cython extension..."
    ${RPATH_FIX_PRE_VAR} python3 setup.py build_ext --inplace

    SO_EXT=$(find build/ -name "*.so" 2>/dev/null | head -1)
    if [ -z "$SO_EXT" ]; then
        echo "ERROR: Cython build produced no .so file."
        echo "Check compiler output above for errors."
        exit 1
    fi
    cp "$SO_EXT" "$SCRIPT_DIR/"

    ${RPATH_FIX_POST_VAR}
"###,
        name = name
    );

    let wheel_steps = if emit_wheel {
        format!(
            r###"
echo "[5/6] Building wheel..."
python3 -m build --wheel --no-isolation

echo "[6/6] Repairing wheel..."
if [ "$OS_NAME" = "Darwin" ]; then
    if command -v delocate-wheel >/dev/null 2>&1; then
        delocate-wheel -v dist/*.whl
    else
        echo "WARNING: delocate-wheel not found. Wheel may not be portable.\nInstall with: pip install delocate"
    fi
else
    if command -v auditwheel >/dev/null 2>&1; then
        auditwheel repair dist/*.whl
        # auditwheel repair puts the repaired wheel in wheelhouse/
        if [ -d "wheelhouse" ]; then
            mv wheelhouse/*.whl dist/
            rm -rf wheelhouse
        fi
    else
        echo "WARNING: auditwheel not found. Wheel may not be portable.\nInstall with: sudo apt install auditwheel (Ubuntu) or pip install auditwheel"
    fi
fi
"###
        )
    } else {
        "".to_string()
    };

    let local_install_success_message = "Local build complete.";

    let footer = format!(
        r###"
echo "[{step_num}/5] Verifying import..."
if python3 -c "import ${{LIB_NAME}}; print(\'${{LIB_NAME}} imported successfully\')"; then
    echo ""
    echo "SUCCESS. {local_install_success_message}"
    {wheel_msg}
else
    echo "ERROR: import failed after successful build."
    if [ "$OS_NAME" = "Darwin" ]; then
        echo "Run: otool -L ${{LIB_NAME}}*.so to diagnose missing libraries."
    else
        echo "Run: ldd ${{LIB_NAME}}*.so to diagnose missing libraries."
    fi
    exit 1
fi
"###,
        step_num = if emit_wheel { "7" } else { "5" },
        wheel_msg = if emit_wheel {
            format!("echo \"Wheel generated in dist/: pip install dist/{}-*.whl\"", name)
        } else {
            "".to_string()
        },
        local_install_success_message = local_install_success_message,
    );

    let mut out = start;
    out.push_str(&wheel_steps);
    out.push_str(&footer);
    out
}
