use crate::ir::{Module, TypeRef};
use crate::shim_planner;

fn prim_to_rust(t: &TypeRef) -> String {
    match t {
        TypeRef::Primitive(k) => match k {
            crate::ir::PrimKind::I8 => "i8".into(),
            crate::ir::PrimKind::I16 => "i16".into(),
            crate::ir::PrimKind::I32 => "i32".into(),
            crate::ir::PrimKind::I64 => "i64".into(),
            crate::ir::PrimKind::U8 => "u8".into(),
            crate::ir::PrimKind::U16 => "u16".into(),
            crate::ir::PrimKind::U32 => "u32".into(),
            crate::ir::PrimKind::U64 => "u64".into(),
            crate::ir::PrimKind::F32 => "f32".into(),
            crate::ir::PrimKind::F64 => "f64".into(),
            crate::ir::PrimKind::Bool => "bool".into(),
            crate::ir::PrimKind::Usize => "usize".into(),
        },
        TypeRef::Named(n) => n.clone(),
        TypeRef::Void => "()".into(),
        other => format!("/*unsupported rust type: {:?}*/", other),
    }
}

fn type_for_sig(t: &TypeRef) -> String {
    match t {
        TypeRef::Named(n) => format!("super::{}", n),
        other => prim_to_rust(other),
    }
}

pub fn generate_shim(module: &Module) -> String {
    use std::collections::HashSet;

    let mut need_cstr = false;
    let mut need_cchar = false;
    let mut named_structs: HashSet<String> = HashSet::new();

    let mut out = String::new();

    // Plan shims and collect needs
    let shims: Vec<crate::ir::ShimFn> = module
        .functions
        .iter()
        .map(|f| shim_planner::plan_shim(f))
        .collect();

    for shim in &shims {
        // params
        for p in &shim.params {
            match &p.original_ty {
                TypeRef::Str => {
                    need_cstr = true;
                    need_cchar = true;
                }
                TypeRef::Named(n) => {
                    named_structs.insert(n.clone());
                }
                TypeRef::Vec(inner) | TypeRef::Option(inner) => {
                    if let TypeRef::Named(n) = &**inner {
                        named_structs.insert(n.clone());
                    }
                }
                _ => {}
            }
            // ffi ty may also indicate cstr
            match &p.ffi_ty {
                crate::ir::FfiType::CStr
                | crate::ir::FfiType::StringSlicePtr
                | crate::ir::FfiType::StringArrayOut => {
                    need_cstr = true;
                    need_cchar = true;
                }
                _ => {}
            }
        }
        // returns
        match &shim.ret {
            TypeRef::Str => {
                need_cstr = true;
                need_cchar = true;
            }
            TypeRef::Named(n) => {
                named_structs.insert(n.clone());
            }
            TypeRef::Vec(inner) | TypeRef::Option(inner) => {
                if let TypeRef::Named(n) = &**inner {
                    named_structs.insert(n.clone());
                }
            }
            _ => {}
        }
        match &shim.ffi_ret {
            crate::ir::FfiType::CStr
            | crate::ir::FfiType::ResultWithErrOut { .. }
            | crate::ir::FfiType::StringSlicePtr
            | crate::ir::FfiType::StringArrayOut => {
                need_cstr = true;
                need_cchar = true;
            }
            _ => {}
        }
    }

    out.push_str("// Auto-generated by rust2cython. Add this file to your crate.\n");
    out.push_str("// Call super::<fn_name>(...) to invoke your original functions.\n\n");

    if need_cstr {
        out.push_str("use std::ffi::{CStr, CString};\n");
    }
    if need_cchar {
        out.push_str("use std::os::raw::c_char;\n");
    }

    out.push_str("\n");

    // comments for named structs
    for name in named_structs.iter() {
        out.push_str(&format!(
            "// Ensure {} is #[repr(C)] in your original code\n",
            name
        ));
    }
    if !named_structs.is_empty() {
        out.push_str("\n");
    }

    // Emit each shim
    for shim in &shims {
        // check for unsupported in params
        let mut skip_due_to_param = None;
        for p in &shim.params {
            if let crate::ir::FfiType::Unsupported(msg) = &p.ffi_ty {
                // print warning to stderr
                eprintln!("WARNING: skipping fn '{}' — {}", shim.original_name, msg);
                // emit explanatory SKIPPED comment in shim file
                out.push_str(&format!(
                    "// SKIPPED: fn {}\n// Reason: {}\n// Unsupported type — implement this FFI wrapper manually.\n\n",
                    shim.original_name, msg
                ));
                skip_due_to_param = Some(msg.clone());
                break;
            }
        }
        if let crate::ir::FfiType::Unsupported(msg) = &shim.ffi_ret {
            eprintln!("WARNING: skipping fn '{}' — {}", shim.original_name, msg);
            out.push_str(&format!(
                "// SKIPPED: fn {}\n// Reason: {}\n// Unsupported type — implement this FFI wrapper manually.\n\n",
                shim.original_name, msg
            ));
            continue;
        }
        if let Some(msg) = skip_due_to_param {
            // already emitted above
            continue;
        }

        // build function signature
        let mut sig = String::new();
        sig.push_str(&format!(
            "#[no_mangle]\npub unsafe extern \"C\" fn {}(",
            shim.shim_name
        ));
        // params
        let mut first = true;
        for p in &shim.params {
            if !first {
                sig.push_str(", ");
            } else {
                first = false;
            }
            match &p.ffi_ty {
                crate::ir::FfiType::Direct(orig) => {
                    let ty = type_for_sig(orig);
                    sig.push_str(&format!("{}: {}", p.name, ty));
                }
                crate::ir::FfiType::CStr => {
                    sig.push_str(&format!("{}: *const c_char", p.name));
                }
                crate::ir::FfiType::SlicePtr { inner } => {
                    let ty = prim_to_rust(inner);
                    sig.push_str(&format!("{}: *const {}, {}_len: usize", p.name, ty, p.name));
                }
                crate::ir::FfiType::OptionPtr { inner } => {
                    let ty = prim_to_rust(inner);
                    sig.push_str(&format!("{}: *const {}", p.name, ty));
                }
                crate::ir::FfiType::StringSlicePtr => {
                    sig.push_str(&format!(
                        "{}: *const *const c_char, {}_len: usize",
                        p.name, p.name
                    ));
                }
                crate::ir::FfiType::Unsupported(msg) => {
                    sig.push_str(&format!("/* SKIPPED param {}: {} */", p.name, msg));
                }
                _ => {
                    sig.push_str(&format!("/* unhandled param type for {} */", p.name));
                }
            }
        }

        // return and extra params for returns
        let mut ret_str = String::new();
        match &shim.ffi_ret {
            crate::ir::FfiType::Direct(orig) => {
                let ty = type_for_sig(orig);
                ret_str = ty;
            }
            crate::ir::FfiType::CStr => {
                ret_str = "*const c_char".into();
            }
            crate::ir::FfiType::SliceOut { inner } => {
                let ty = prim_to_rust(inner);
                // add out params
                if !first {
                    sig.push_str(", ");
                } else {
                    first = false;
                }
                sig.push_str(&format!("out: *mut {}, out_len: usize", ty));
                ret_str = "()".into();
            }
            crate::ir::FfiType::OptionPtr { inner } => {
                let ty = prim_to_rust(inner);
                ret_str = format!("*const {}", ty);
            }
            crate::ir::FfiType::ResultWithErrOut { ok } => {
                let ok_ty = prim_to_rust(ok);
                // add error_out param
                if !first {
                    sig.push_str(", ");
                } else {
                    first = false;
                }
                sig.push_str("error_out: *mut *mut c_char");
                ret_str = ok_ty;
            }
            crate::ir::FfiType::StringArrayOut => {
                if !first {
                    sig.push_str(", ");
                } else {
                    first = false;
                }
                sig.push_str("out_len: *mut usize");
                ret_str = "*mut *mut c_char".into();
            }
            crate::ir::FfiType::Unsupported(msg) => {
                out.push_str(&format!(
                    "// SKIPPED fn {}: {}\n\n",
                    shim.original_name, msg
                ));
                continue;
            }
            _ => {
                out.push_str(&format!(
                    "// SKIPPED fn {}: unsupported return mapping\n\n",
                    shim.original_name
                ));
                continue;
            }
        }

        sig.push_str(&format!(") -> {} {{\n", ret_str));

        // function body: convert args and call super
        let mut body = String::new();
        // build call arg list
        let mut call_args: Vec<String> = Vec::new();
        for p in &shim.params {
            match &p.ffi_ty {
                crate::ir::FfiType::Direct(orig) => {
                    call_args.push(p.name.clone());
                }
                crate::ir::FfiType::CStr => {
                    if let crate::ir::TypeRef::Str = &p.original_ty {
                        body.push_str(&format!("    let {0}_s = unsafe {{ CStr::from_ptr({0}).to_str().unwrap().to_owned() }};\n", p.name));
                        call_args.push(format!("{}_s", p.name));
                    } else {
                        body.push_str(&format!("    let {0}_s = if {0}.is_null() {{ None }} else {{ Some(unsafe {{ CStr::from_ptr({0}).to_str().unwrap().to_owned() }}) }};\n", p.name));
                        call_args.push(format!("{}_s", p.name));
                    }
                }
                crate::ir::FfiType::SlicePtr { inner } => {
                    body.push_str(&format!(
                        "    let {}_slice = unsafe {{ std::slice::from_raw_parts({}, {}_len) }};\n",
                        p.name, p.name, p.name
                    ));
                    call_args.push(format!("{}_slice.to_vec()", p.name));
                }
                crate::ir::FfiType::OptionPtr { inner } => {
                    let ty = prim_to_rust(inner);
                    body.push_str(&format!("    let {}_opt = if {}.is_null() {{ None }} else {{ Some(unsafe {{ *{} }}) }};\n", p.name, p.name, p.name));
                    call_args.push(format!("{}_opt", p.name));
                }
                crate::ir::FfiType::StringSlicePtr => {
                    body.push_str(&format!(
                        "    let {}_slice = unsafe {{ std::slice::from_raw_parts({}, {}_len) }};\n",
                        p.name, p.name, p.name
                    ));
                    body.push_str(&format!(
                        "    let {}_vec: Vec<String> = {}_slice.iter().map(|&ptr| unsafe {{ CStr::from_ptr(ptr).to_str().unwrap().to_owned() }}).collect();\n",
                        p.name, p.name
                    ));
                    call_args.push(format!("{}_vec", p.name));
                }
                _ => {}
            }
        }

        // now generate call/return per ffi_ret
        match &shim.ffi_ret {
            crate::ir::FfiType::Direct(_) => {
                body.push_str(&format!(
                    "    return super::{}({});\n",
                    shim.original_name,
                    call_args.join(", ")
                ));
            }
            crate::ir::FfiType::CStr => {
                body.push_str(&format!(
                    "    let result = super::{}({});\n",
                    shim.original_name,
                    call_args.join(", ")
                ));
                if let crate::ir::TypeRef::Str = &shim.ret {
                    body.push_str("    CString::new(result).unwrap().into_raw()\n");
                } else {
                    body.push_str("    match result { Some(s) => CString::new(s).unwrap().into_raw(), None => std::ptr::null_mut() }\n");
                }
            }
            crate::ir::FfiType::SliceOut { .. } => {
                body.push_str(&format!(
                    "    let v = super::{}({});\n",
                    shim.original_name,
                    call_args.join(", ")
                ));
                body.push_str("    let out_slice = unsafe { std::slice::from_raw_parts_mut(out, out_len.min(v.len())) };\n");
                body.push_str("    out_slice.copy_from_slice(&v[..out_slice.len()]);\n");
            }
            crate::ir::FfiType::OptionPtr { .. } => {
                body.push_str(&format!(
                    "    match super::{}({}) {{\n",
                    shim.original_name,
                    call_args.join(", ")
                ));
                body.push_str("        Some(v) => Box::into_raw(Box::new(v)),\n");
                body.push_str("        None => std::ptr::null(),\n");
                body.push_str("    }\n");
            }
            crate::ir::FfiType::ResultWithErrOut { .. } => {
                body.push_str(&format!(
                    "    match super::{}({}) {{\n",
                    shim.original_name,
                    call_args.join(", ")
                ));
                body.push_str(
                    "        Ok(v) => { unsafe { *error_out = std::ptr::null_mut(); } v },\n",
                );
                body.push_str("        Err(e) => { unsafe { *error_out = CString::new(e.to_string()).unwrap().into_raw(); } Default::default() },\n");
                body.push_str("    }\n");
            }
            crate::ir::FfiType::StringArrayOut => {
                body.push_str(&format!(
                    "    let v = super::{}({});\n",
                    shim.original_name,
                    call_args.join(", ")
                ));
                body.push_str("    let mut c_strs: Vec<*mut c_char> = v.into_iter().map(|s| CString::new(s).unwrap().into_raw()).collect();\n");
                body.push_str("    c_strs.push(std::ptr::null_mut());\n");
                body.push_str("    let len = c_strs.len() - 1;\n");
                body.push_str("    unsafe { *out_len = len; }\n");
                body.push_str("    Box::into_raw(c_strs.into_boxed_slice()) as *mut *mut c_char\n");
            }
            _ => {
                // handled above
            }
        }

        out.push_str(&sig);
        out.push_str(&body);
        out.push_str("}\n\n");
    }

    // free helper
    if need_cstr {
        out.push_str(
            "#[no_mangle]\npub extern \"C\" fn rust2cython_free_string(ptr: *mut c_char) {\n",
        );
        out.push_str("    if !ptr.is_null() { unsafe { drop(CString::from_raw(ptr)); } }\n");
        out.push_str("}\n\n");

        out.push_str(
            "#[no_mangle]\npub unsafe extern \"C\" fn rust2cython_free_string_array(ptr: *mut *mut c_char, len: usize) {\n",
        );
        out.push_str("    if !ptr.is_null() {\n");
        out.push_str(
            "        let slice = Box::from_raw(std::slice::from_raw_parts_mut(ptr, len + 1));\n",
        );
        out.push_str("        for &item in slice.iter() {\n");
        out.push_str("            if !item.is_null() {\n");
        out.push_str("                drop(CString::from_raw(item));\n");
        out.push_str("            }\n");
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n");
    }

    out
}
